swagger: '2.0'
info:
  version: "1.0.0"
  title: Zoo API
  description: API for managing zoo operations
paths:
  /animals:
    get:
      summary: Retrieve a list of all animals
      responses:
        200:
          description: A list of animals
    post:
      summary: Add a new animal
      parameters:
        - in: body
          name: animal
          description: The animal to create
          schema:
            type: object
            required:
              - species
              - age
              - gender
              - special_requirements
            properties:
              species:
                type: string
              age:
                type: integer
              gender:
                type: string
              special_requirements:
                type: string
      responses:
        201:
          description: Animal created
  /animals/{id}:
    get:
      summary: Retrieve a specific animal by its id
      parameters:
        - in: path
          name: id
          required: true
          type: integer
      responses:
        200:
          description: An animal
        404:
          description: Animal not found
    put:
      summary: Update an existing animal by its id
      parameters:
        - in: path
          name: id
          required: true
          type: integer
        - in: body
          name: animal
          description: The animal to update
          schema:
            type: object
            properties:
              species:
                type: string
              age:
                type: integer
              gender:
                type: string
              special_requirements:
                type: string
      responses:
        200:
          description: Animal updated
        404:
          description: Animal not found
    delete:
      summary: Delete an existing animal by its id
      parameters:
        - in: path
          name: id
          required: true
          type: integer
      responses:
        200:
          description: Animal deleted
        404:
          description: Animal not found
  /employees:
    get:
      summary: Retrieve a list of all employees
      responses:
        200:
          description: A list of employees
    post:
      summary: Add a new employee
      parameters:
        - in: body
          name: employee
          description: The employee to create
          schema:
            type: object
            required:
              - name
              - email
              - phone_number
              - role
              - schedule
            properties:
              name:
                type: string
              email:
                type: string
              phone_number:
                type: string
              role:
                type: string
              schedule:
                type: string
      responses:
        201:
          description: Employee created
  /employees/{id}:
    get:
      summary: Retrieve a specific employee by their id
      parameters:
        - in: path
          name: id
          required: true
          type: integer
      responses:
        200:
          description: An employee
        404:
          description: Employee not found
    put:
      summary: Update an existing employee by their id
      parameters:
        - in: path
          name: id
          required: true
          type: integer
        - in: body
          name: employee
          description: The employee to update
          schema:
            type: object
            properties:
              name:
                type: string
              email:
                type: string
              phone_number:
                type: string
              role:
                type: string
              schedule:
                type: string
      responses:
        200:
          description: Employee updated
        404:
          description: Employee not found
    delete:
      summary: Delete an existing employee by their id
      parameters:
        - in: path
          name: id
          required: true
          type: integer
      responses:
        200:
          description: Employee deleted
        404:
          description: Employee not found